### ISSUE TITLE
Change doc comment to throw ResultException

### ISSUE THREAD

**Issue by cundd** [prewk/result#8]
`unwrap()` appears to throw a `ResultException` on error, but the doc comment mentions `\Exception` (see https://github.com/prewk/result/blob/master/src/Result.php#L164).

Is it possible to change the doc comment?

In the IDE PhpStorm this would be handy to add `ResultException` to the list of "Unchecked Exceptions".

**Comment by cundd** [comment]
Btw: Great library. We now only need the ?-operator 😄

**Comment by andrew-demb** [comment]
I thought so too, while improve phpdocs.
But Err class support pass in constructor exception and throw this in unwrap stop me from it.

See: https://github.com/prewk/result/blob/70add2dabb799541f4cd23bccd27b0e61193a34e/src/Result/Err.php#L224

**Comment by cundd** [comment]
Ah, yeah. Of course. That makes sense.

Thank you for the answer.

**Comment by prewk** [comment]
Ah, yeah I think my reasoning was that "it throws something that _is_ or _extends_  `\Exception`". By default it's `ResultException` but I've almost always used it with custom exceptions to make things grouped nicely at Sentry etc.
